[build]
builder = "dockerfile"

[deploy]
startCommand = "./start-services.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
# Required environment variables
WHATSAPP_PHONE_NUMBER = "+27640412391"

# Note: WhatsApp session persistence now handled via PostgreSQL database
# instead of Railway volumes due to volume configuration limitations
# Railway will use environment variables set in dashboard
# These are defaults that can be overridden
PORT = "8080"
LOG_LEVEL = "INFO"
DEBUG_MODE = "false"
