[build]
builder = "dockerfile"

[deploy]
startCommand = "./start-services.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[volumes]
# Persistent storage for WhatsApp session data
# This prevents having to re-authenticate on every deployment
store = "/app/store"
logs = "/app/logs"

[variables]
# Railway will use environment variables set in dashboard
# These are defaults that can be overridden
PORT = "8080"
LOG_LEVEL = "INFO"
DEBUG_MODE = "false"
