[build]
builder = "dockerfile"

[deploy]
startCommand = "./start-services.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
# Railway will use environment variables set in dashboard
# These are defaults that can be overridden
PORT = "8080"
LOG_LEVEL = "INFO"
DEBUG_MODE = "false"